### ISSUE TITLE
gitolite/vagrant installation issues

### ISSUE THREAD

**Issue by reidka** [MarkUsProject/Markus#2211]
@david-yz-liu and I were trying to test the instructions for using gitolite and vagrant and came up with the following issues:

- the vagrant vm already has a git user with most of gitolite installed, so we first tried to bypass the gitolite install instructions.  
- there is a git.pub file in the git user home directory that we thought should be named vagrant.pub
- the .gitolite/keydir already had some directories in it 
- config environments files did not have a matching pair of paths for the public private keys.  The private key should have been /home/git/vagrant.pub
- the MarkUs git_repository code hard-code the 'git' user for adding permissions.  (We had to change it to 'vagrant' to get it to work.)  This really should be a configurable parameter.

@oneohtrix I think we need to delete the 'git' user and recreate it but stop just after cloning the gitolite repo.  (@david-yz-liu and I had a really hard time trying to back out and redo steps because it was too hard to figure out all the different files that were getting modified by each step.)

**Comment by oneohtrix** [comment]
hmm, okay. I'll take another stab at this. what are the steps I can perform to verify that gitolite works 100%?

**Comment by david-yz-liu** [comment]
Really all we'd like to see is the Vagrant machine going up to step #9 in the [wiki](https://github.com/MarkUsProject/Markus/wiki/SettingUpVagrantEnvironment) under "install Gitolite".

You don't need to make sure gitolite "works" at that point (it won't), but the rest of the installation should work after it.

In fact, proceeding with the installation and setup will create new directories that we don't want to see in the virtual machine.

**Comment by reidka** [comment]
Thanks @oneohtrix!  You can save, or make a copy of the the vm at this point, and then continue with the installation instructions to make sure that they work.

**Comment by oneohtrix** [comment]
Okay, I updated the box again with the recreated git user and vagrant.pub key. Hopefully it works this time. Please test it out and let me know if there are any issues -- I tested up until I saw the `hello vagrant` message.

**Comment by david-yz-liu** [comment]
@reidka Can you test this some time soon? I've also merged master into the git branch, so you can try on the newest version. Thanks!

**Comment by david-yz-liu** [comment]
And thanks @oneohtrix!

**Comment by reidka** [comment]
@oneohtrix and @david-yz-liu it is better, but I'm still getting the 
Rugged::NetworkError: Early EOF

And when I 'ssh -T git@localhost'  I get

hello vagrant, this is git@vagrant-ubuntu-trusty-64 running gitolite3 v3.6.3-10-g4be7ac5 on git 1.9.1

 R W    testing

Without the R W gitolite-admin

I'll try to look into this more, but I have to get something else done today.

**Comment by reidka** [comment]
@oneohtrix I was able to get the gitolite-admin to work by deleting
.gitolite
.gitolite.rc
repositories
.ssh

Do we need git.pub ?  It was the same as the vagrant public key until I created a new one, so my guess is that we don't.

**Comment by oneohtrix** [comment]
@reidka I don't think those files should be in the new vagrant box..I'm quite certain the keys are set up properly and all that needs to be done is to `mkdir bin` and install gitolite under git.

However, I have been trying to get Markus set up with git, and I get the following error every time I perform rake db:setup (per the instructions in the wiki):
```
Grit::InvalidGitRepositoryError: /home/vagrant/Markus/data/dev/repos/conf
/home/vagrant/.rvm/gems/ruby-2.1.3@markus/gems/grit-2.5.0/lib/grit/repo.rb:51:in `initialize'
/home/vagrant/.rvm/gems/ruby-2.1.3@markus/gems/gitolite-1.1.0/lib/gitolite/gitolite_admin.rb:16:in `new'
/home/vagrant/.rvm/gems/ruby-2.1.3@markus/gems/gitolite-1.1.0/lib/gitolite/gitolite_admin.rb:16:in `initialize'
```
-- you mentioned that the git_repository code hard-coded the git user, is this related to that?

cc @david-yz-liu, @SoftwareDev, roping you in since you know how the git library code works.

**Comment by david-yz-liu** [comment]
@oneohtrix Okay, maybe the wrong vagrant box version was used.

You probably need to delete everything in the `data/dev/repos` folder before doing the setup.

**Comment by oneohtrix** [comment]
Hi @reidka and @david-yz-liu, sorry for dawdling. I took another stab at the Vagrant box with git today. I managed to get MarkUs into a semi-working state with git. I don't think the problems I encountered were related to the Vagrant build, though. Here are the steps I did, starting from a totally clean box:

`vagrant up` (make sure box is on version 1.2; check using `vagrant box list`)
`vagrant ssh` (password is vagrant)
`su git` (password is also vagrant)
cd into git home directory
`mkdir bin`
`gitolite/install -ln`
`export PATH="~/bin:$PATH"`
`gitolite setup -pk vagrant.pub`
`exit`
`cd into vagrant home directory`
`eval $(ssh-agent -s)`
`ssh-add ~/.ssh/id_rsa`
`ssh -T git@localhost` (ensure we get 'hello' message)
`git config --global user.name "Lawrence Wu"`
`git config --global user.email "lawrence@email.com"`
`git clone https://github.com/MarkUsProject/Markus.git`
`cd Markus`
`edit config/environments/development.rb to change REPOSITORY_TYPE from svn to git`
`bundle install`
`cp ~/database.yml config`
`mkdir data/dev/repos`
`bundle exec rake db:setup`
`...wait a really long time`

At this point, I received the following error:
```
No revision found before supplied timestamp.
/home/vagrant/Markus/lib/repo/git_repository.rb:335:in `get_revision_by_timestamp'
/home/vagrant/Markus/app/models/submission.rb:23:in `create_by_timestamp'
/home/vagrant/Markus/lib/tasks/marks.rake:20:in `block (3 levels) in <top (required)>'
/home/vagrant/.rvm/gems/ruby-2.1.3@markus/gems/activerecord-4.2.3/lib/active_record/relation/delegation.rb:46:in `each'
/home/vagrant/.rvm/gems/ruby-2.1.3@markus/gems/activerecord-4.2.3/lib/active_record/relation/delegation.rb:46:in `each'
/home/vagrant/Markus/lib/tasks/marks.rake:18:in `block (2 levels) in <top (required)>'
/home/vagrant/Markus/db/seeds.rb:7:in `<top (required)>'
/home/vagrant/.rvm/gems/ruby-2.1.3@markus/gems/activesupport-4.2.3/lib/active_support/dependencies.rb:268:in `load'
/home/vagrant/.rvm/gems/ruby-2.1.3@markus/gems/activesupport-4.2.3/lib/active_support/dependencies.rb:268:in `block in load'
/home/vagrant/.rvm/gems/ruby-2.1.3@markus/gems/activesupport-4.2.3/lib/active_support/dependencies.rb:240:in `load_dependency'
/home/vagrant/.rvm/gems/ruby-2.1.3@markus/gems/activesupport-4.2.3/lib/active_support/dependencies.rb:268:in `load'
/home/vagrant/.rvm/gems/ruby-2.1.3@markus/gems/railties-4.2.3/lib/rails/engine.rb:547:in `load_seed'
/home/vagrant/.rvm/gems/ruby-2.1.3@markus/gems/activerecord-4.2.3/lib/active_record/tasks/database_tasks.rb:250:in `load_seed'
/home/vagrant/.rvm/gems/ruby-2.1.3@markus/gems/activerecord-4.2.3/lib/active_record/railties/databases.rake:180:in `block (2 levels) in <top (required)>'
/home/vagrant/.rvm/gems/ruby-2.1.3@markus/bin/ruby_executable_hooks:15:in `eval'
/home/vagrant/.rvm/gems/ruby-2.1.3@markus/bin/ruby_executable_hooks:15:in `<main>'
Tasks: TOP => db:marks
```

The folders and files in `data/dev/repos` looked alright though, so I started up the rails server and looked around in the submissions for A1. When trying to access the repo view for a submission, I received the following stack trace:
```
undefined method `__get_files' for #<Repository::GitRevision:0x000000083e2be8>
lib/repo/git_repository.rb:1111:in `files_at_path_helper'
lib/repo/git_repository.rb:1097:in `changed_files_at_path'
app/controllers/submissions_controller.rb:87:in `block in repo_browser'
app/controllers/submissions_controller.rb:78:in `times'
app/controllers/submissions_controller.rb:78:in `each'
app/controllers/submissions_controller.rb:78:in `repo_browser'
```

As I said, these look like programming errors instead of environment issues. Could someone confirm? If so, I'd like to close this issue since I believe the vagrant box is correctly set up.

**Comment by david-yz-liu** [comment]
@oneohtrix Thanks, you're correct that these are issues with the software and not the vagrant machine. I'll close the issue after we get someone to download the new vagrant box.

**Comment by david-yz-liu** [comment]
@oneohtrix Good to go.
